[package]
name = "game"
version = "0.1.0"
authors = ["Jack Britton <jackxbritton@gmail.com>"]
edition = "2018"

[dependencies]
generational-arena = "0.2"
half = "1.6.0"
nalgebra = "0.20"
serde = { version = "1.0", features = ["derive"] }
